spring.application.name=crudReact
server.port= 8989

debug=true

spring.datasource.url=jdbc:postgresql://localhost:5432/springsec_react?logUnclosedConnections=true&currentSchema=public&reWriteBatchedInserts=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=vidhi123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=vidhi177
spring.data.redis.timeout=2000
spring.data.redis.database=1






