spring.application.name=crudReact
server.port= 8989

debug=true

spring.datasource.url=jdbc:postgresql://localhost:5432/springsec_react?logUnclosedConnections=true&currentSchema=public&reWriteBatchedInserts=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=vidhi123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update





